import IntroLoader from "./Components/IntroLoader";
import "./globals.css";
import localFont from "next/font/local";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Lalezar = localFont({
  src: [{ path: "../../public/fonts/Lalezar-Regular.ttf" }],
  variable: "--font-lalezar"
});
const Poppins = localFont({
  src: [{ path: "../../public/fonts/Poppins-Regular.ttf" }],
  variable: "--font-poppins"
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
         className={`${Lalezar.variable} ${Poppins.variable}  antialiased`}
         cz-shortcut-listen="true"
      >
        <IntroLoader>{children}</IntroLoader>
      </body>
    </html>
  );
}
